.section .text, "ax"
_start:
    add r0, r1, r2
    add r0, r0, r0
    add r1, r1, r1
    add r2, r2, r2
    add r3, r3, r3
    add r4, r4, r4
    add r5, r5, r5
    add r6, r6, r6
    add r7, r7, r7
    add r8, r8, r8
    add r9, r9, r9
    add r10, r10, r10
    add r11, r11, r11
    add r12, r12, r12
    add r13, r13, r13
    add r14, r14, r14
    add r15, r15, r15
    add sp, sp, sp
    add lr, lr, lr
    add pc, pc, pc
