.section .text, "ax"
_start:
    and r0, r1, r2
    and r0, r0, r0
    and r1, r1, r1
    and r2, r2, r2
    and r3, r3, r3
    and r4, r4, r4
    and r5, r5, r5
    and r6, r6, r6
    and r7, r7, r7
    and r8, r8, r8
    and r9, r9, r9
    and r10, r10, r10
    and r11, r11, r11
    and r12, r12, r12
    and r13, r13, r13
    and r14, r14, r14
    and r15, r15, r15
    and sp, sp, sp
    and lr, lr, lr
    and pc, pc, pc
