.section .text, "ax"
_start:
    and r0, r1, #2
    and r0, r0, #1
    and r1, r1, #1
    and r2, r2, #1
    and r3, r3, #1
    and r4, r4, #1
    and r5, r5, #1
    and r6, r6, #1
    and r7, r7, #1
    and r8, r8, #1
    and r9, r9, #1
    and r10, r10, #1
    and r11, r11, #1
    and r12, r12, #1
    and r13, r13, #1
    and r14, r14, #1
    and r15, r15, #1
    and sp, sp, #1
    and lr, lr, #1
    and pc, pc, #1
