.section .text, "ax"
_start:
    orr r0, r1, r2
    orr r0, r0, r0
    orr r1, r1, r1
    orr r2, r2, r2
    orr r3, r3, r3
    orr r4, r4, r4
    orr r5, r5, r5
    orr r6, r6, r6
    orr r7, r7, r7
    orr r8, r8, r8
    orr r9, r9, r9
    orr r10, r10, r10
    orr r11, r11, r11
    orr r12, r12, r12
    orr r13, r13, r13
    orr r14, r14, r14
    orr r15, r15, r15
    orr sp, sp, sp
    orr lr, lr, lr
    orr pc, pc, pc
