.section .text, "ax"
_start:
    orr r0, r1, #2
    orr r0, r0, #1
    orr r1, r1, #1
    orr r2, r2, #1
    orr r3, r3, #1
    orr r4, r4, #1
    orr r5, r5, #1
    orr r6, r6, #1
    orr r7, r7, #1
    orr r8, r8, #1
    orr r9, r9, #1
    orr r10, r10, #1
    orr r11, r11, #1
    orr r12, r12, #1
    orr r13, r13, #1
    orr r14, r14, #1
    orr r15, r15, #1
    orr sp, sp, #1
    orr lr, lr, #1
    orr pc, pc, #1
