.section .text, "ax"
_start:
    sub r0, r1, #2
    sub r0, r0, #1
    sub r1, r1, #1
    sub r2, r2, #1
    sub r3, r3, #1
    sub r4, r4, #1
    sub r5, r5, #1
    sub r6, r6, #1
    sub r7, r7, #1
    sub r8, r8, #1
    sub r9, r9, #1
    sub r10, r10, #1
    sub r11, r11, #1
    sub r12, r12, #1
    sub r13, r13, #1
    sub r14, r14, #1
    sub r15, r15, #1
    sub sp, sp, #1
    sub lr, lr, #1
    sub pc, pc, #1
