name: Build and test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install arm-none-eabi-gcc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-arm-none-eabi
      
      - name: Build and test
        run: |
          make clean
          make test
